#!/usr/bin/env python
"""
	@author: Jean-Lou Dupont
"""
## for development environment
import os
import sys

DEBUG=False

if "_DEBUG" in os.environ:
	print ">> Debug mode entered"
	DEBUG=True
	this_dir=os.path.dirname(__file__)
	lib_path=os.path.abspath(os.path.join(this_dir, ".."))
	sys.path.insert(0, lib_path)

from MediaKeysServer.scripts.main import main, options

## There is no 'argparse' module
##  on OSX / Python 2.6
try:
	import argparse
	parser=argparse.ArgumentParser(prog="MediaKeysServer")
	for option in options:
		name, action, default, help=option
		parser.add_argument(name, action=action, default=default, help=help)
		
	args=parser.parse_args()
except:
	args={}
	

this_path=os.path.abspath(__file__)
try:
	main(args, this_path, DEBUG)
except KeyboardInterrupt:
	print "\nExiting..."
	sys.exit(1)
